### ISSUE TITLE
Bug: Writing an object column with NaN value throws exception

### ISSUE THREAD

**Issue by oliverlewis** [tebeka/fastavro#99] opened 2017-09-11 22:52 UTC
Exception:
nan (type <type 'float'>) do not match ['null', 'string']

Expected output:
nan should be converted to null.

**Comment by scottbelden** [comment] 2017-09-12 00:37
Could you provide more context? This doesn't seem like a problem. Your schema expects a string or null and you have given it a float. A `NaN` should not be implicitly converted to `None` otherwise when you read the record out it won't match.

Here's an example showing that it should be possible to serialize/de-serialize a `NaN`

```python
In [8]: from io import BytesIO
   ...: from fastavro import writer, reader
   ...: 
   ...: schema = {
   ...:     'name': 'NaN',
   ...:     'namespace': 'test',
   ...:     'type': 'record',
   ...:     'fields': [
   ...:         {'name': 'test_nan', 'type': 'float'},
   ...:     ],
   ...: }
   ...: 
   ...: records = [
   ...:     {u'test_nan': float('nan')},
   ...: ]
   ...: 
   ...: fo = BytesIO()
   ...: 
   ...: writer(fo, schema, records)
   ...: 
   ...: fo.seek(0)
   ...: 
   ...: read_records = list(reader(fo))
   ...: 
   ...: print(records)
   ...: print(read_records)
   ...: 
[{'test_nan': nan}]
[{'test_nan': nan}]
```

**Comment by oliverlewis** [comment] 2017-09-12 17:15
Let me elaborate:

I have a pandas dataframe column called CITY<String> which contains 'nan'. This is not a column of type float.

**Comment by tebeka** [comment] 2017-09-12 17:42
@oliverlewis What is the `dtype` of the `CITY` column?

**Comment by oliverlewis** [comment] 2017-09-12 17:48
city                        object

**Comment by scottbelden** [comment] 2017-09-12 20:38
Could you provide some code that reproduces the problem?

**Comment by oliverlewis** [comment] 2017-09-12 21:21
[FastAvroBug.pdf](https://github.com/tebeka/fastavro/files/1297468/FastAvroBug.pdf)

**Comment by kkirsanov** [comment] 2017-09-14 10:14
@oliverlewis 
Can you provide a more compact example?

**Comment by scottbelden** [comment] 2018-05-12 20:48
@oliverlewis Sorry that this hasn't seen much attention. I looked at the pdf that you posted, but I can't run it because it tries to open a file that you might have had but I don't (`data/sample_skout_userdata.json`). If this is still relevant would you be able to provide an example with the necessary resources?

**Comment by scottbelden** [comment] 2018-05-18 19:32
I'm going to close this. If it's still relevant and there is a good way to reproduce it, please re-open.

**Closed by scottbelden** 2018-05-18 19:32 UTC
