### ISSUE TITLE
doubles getting set to 'zero' on windows

### ISSUE THREAD

**Issue by dtedder** [tebeka/fastavro#154] opened 2018-02-01 15:52 UTC
'double' values get set to values like: 6.9527827306242e-310.  but switching the type to 'float' gives the expected value.

seems like same issue as #125 .  but versions have been updated since.

Python - 3.6.4
fastavro - 0.17.5
cython - 0.27.3

**Comment by scottbelden** [comment] 2018-02-01 16:01
Thanks for the report. Do you have a script that reproduces this failure so that I can add it to the tests and figure out what's going on?

**Comment by dtedder** [comment] 2018-02-01 16:38
```

def main():
	import fastavro as avro
	from fastavro import writer

	schema = {
		'doc': 'A weather reading.',
		'name': 'Weather',
		'namespace': 'test',
		'type': 'record',
		'fields': [
			{'name': 'station', 'type': 'string'},
			{'name': 'time', 'type': 'long'},
			{'name': 'temp', 'type': 'int'},
			{'name': 'test_float', 'type': 'double'}
		]
	}

	with open('weather_out.avro', 'wb') as out:
		records = [
			{'station': '011990-99999', 'temp': 0, 'test_float': 0.21334215134123513, 'time': -714214260},
			{'station': '011990-99999', 'temp': 22, 'test_float': 0.21334215134123513, 'time': -714213259},
			{'station': '011990-99999', 'temp': -11, 'test_float': 0.21334215134123513, 'time': -714210269},
			{'station': '012650-99999', 'temp': 111, 'test_float': 0.21334215134123513, 'time': -714208170}
		]
		writer(out, schema, records)

	with open('weather_out.avro', 'rb') as fo:
		reader = avro.reader(fo)
		schema = reader.schema
		for row in reader:
			print(row)

if __name__ == '__main__':
    main()
```

taken from issue #125

**Comment by dtedder** [comment] 2018-02-01 16:38
output is:

```
{'station': '011990-99999', 'time': -714214260, 'temp': 0, 'test_float': 6.9528629697069e-310}
{'station': '011990-99999', 'time': -714213259, 'temp': 22, 'test_float': 6.9528629697069e-310}
{'station': '011990-99999', 'time': -714210269, 'temp': -11, 'test_float': 6.9528629697069e-310}
{'station': '012650-99999', 'time': -714208170, 'temp': 111, 'test_float': 6.9528629697069e-310}
```

**Comment by scottbelden** [comment] 2018-02-01 21:27
I thought I had made a test case for this last time, but I guess I didn't because there wasn't windows testing at the time. I have a [PR](https://github.com/tebeka/fastavro/pull/156) that resolves this (and actually adds a test) so I'll get that merged and released shortly.

**Closed** 2018-02-01 21:30 UTC
